node {
    checkout scm

    docker.image('python:3.11-alpine').inside('-u root:root') {
        stage('Build') {
            sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
        }

        stage('Test') {
            sh 'python3 -m pip install --user pytest'
            sh 'python3 -m pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            junit 'test-reports/results.xml'
        }

        stage('Deliver') {
            sh 'apk add --no-cache binutils'
            sh 'python3 -m pip install --user pyinstaller'
            sh 'python3 -m PyInstaller --onefile sources/add2vals.py'
            archiveArtifacts 'dist/add2vals'
        }
    }
}
